acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 1
      image:
        repository: quay.io/puzzle/gitlab-ci-cd-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations:
          route.openshift.io/termination: edge
          kubernetes.io/ingress.class: nginx-public
        emptyTLS: false
        secretOverride: acend-wildcard
        appname: gitlab-ci-cd-training
        domain: training.acend.ch
    - 
      name: puzzle
      replicaCount: 1
      image:
        repository: quay.io/puzzle/gitlab-ci-cd-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-puzzle"
      ingress:
        emptyTLS: true
        useDefaultSecret: true
        appname: gitlab-ci-cd-training
        domainmain: puzzle.ch
        domain: ocp-internal.cloudscale.puzzle.ch


nameOverride: "puzzle-gitlab-ci-cd-training"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
